services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://db_user:db_password@db:3306/mydb
      REDIS_URL: redis://redis:6379

  db:
    image: mysql:5.7   # Spécifie l'image MySQL à utiliser
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  redis:
    image: redis:latest  # Spécifie l'image Redis à utiliser
    container_name: redis_cache
    ports:
      - "6379:6379"
